const userPlaylistActionTypes = {
  ADD_SONG_TO_USER_PLAYLIST: "ADD_SONG_TO_USER_PLAYLIST",
  REMOVE_SONG_FROM_USER_PLAYLIST: "REMOVE_SONG_FROM_USER_PLAYLIST",
  REMOVE_ALL_SONGS_FROM_USER_PLAYLIST: "REMOVE_ALL_SONGS_FROM_USER_PLAYLIST",
};

export default userPlaylistActionTypes;
