import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";

import { NextAuthProvider } from "@/src/providers/NextAuthProvider";
import { ThemeProvider } from "@/src/components/theme-provider";
import { Theme } from "@radix-ui/themes";

import { NotificationProvider } from "@/src/providers/NotificationContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Set Mix Genea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
      <NextAuthProvider>
          <Theme>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <NotificationProvider>{children}</NotificationProvider>
            </ThemeProvider>
          </Theme>
      </NextAuthProvider>
        </body>
    </html>
  );
}
